name: documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '2'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[yeet]
    - name: Generate documentation
      run: |
        python ./run-pdoc3.py --current-environment
    - name: Upload documentation
      env:
        auth: ${{ secrets.GH_PAGES_TOKEN  }}
      working-directory: ./html/refinery
      shell: bash
      run: |
        git init
        git config user.email "huettenhain@users.noreply.github.com"
        git config user.name jesko
        git remote add origin https://huettenhain:$auth@github.com/binref/binref.github.io
        git add --all
        git commit -m refinery/${{github.sha}}
        git push origin master --force
