# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Linux-specific dependencies
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get install xclip xvfb
    - name: MacOS-specific dependencies
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew install libmagic
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        pip install .
    - name: Unit tests
      if: ${{ matrix.os != 'ubuntu-latest' }}
      run: |
        python -m unittest discover -p test_*.py
    - name: Unit tests
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        XDG_SESSION_TYPE=x11 xvfb-run python -m unittest discover -p test_*.py

  codecov:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install xclip xvfb
        python -m pip install --upgrade pip
        python -m pip install flake8 codecov
        pip install .
    - name: Generate code coverage
      run: |
        XDG_SESSION_TYPE=x11 xvfb-run coverage run --source refinery run-tests.py
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
